### ISSUE TITLE
AttributeError: module 'plistlib' has no attribute '_dateToString'

### ISSUE THREAD

**Issue by bhyde** [twardoch/yaplon#2]
Searching suggests it's not defined.

https://github.com/twardoch/yaplon/search?q=_dateToString&unscoped_q=_dateToString

Example from this binary plist file I'm suffering with:

```
       <key>SoftwareUpdateLastPoll</key>
	<date>2020-02-05T13:04:28Z</date>
```

**Comment by bhyde** [comment]
Hack'd into working?
```
        # obj = plistlib._dateToString(obj)
        obj = plistlib._date_to_string(obj)
```
probably need something for going the other way.

**Comment by twardoch** [comment]
Will fix that
